# Generated by Django 2.2 on 2020-03-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default=8, upload_to='products/'),
            preserve_default=False,
        ),
    ]
